#!/bin/bash

if [ "$BLOCK_BUTTON" ==  "1" ]; then
    playerctl previous
elif [ "$BLOCK_BUTTON" == "2" ]; then
    playerctl play-pause
elif [ "$BLOCK_BUTTON" == "3" ]; then
    playerctl next
fi
playerctl metadata -f "{{artist}} - {{title}}"
playerctl metadata -f "{{artist}} - {{title}}"

STATUS=$(playerctl status)

if [ "$STATUS" == "Playing" ]; then
    echo "#2FFFA1"
elif [ "$STATUS" == "Paused" ]; then
    echo "#A0A0A0"
fi
